/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CriarAgendamento`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Compromisso`; params?: Router.UnknownInputParams; } | { pathname: `/components/DiaDaSemana`; params?: Router.UnknownInputParams; } | { pathname: `/components/Footer`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/ListaDeCompromissos`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/CriarAgendamento`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Compromisso`; params?: Router.UnknownOutputParams; } | { pathname: `/components/DiaDaSemana`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Footer`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ListaDeCompromissos`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/CriarAgendamento${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/Compromisso${`?${string}` | `#${string}` | ''}` | `/components/DiaDaSemana${`?${string}` | `#${string}` | ''}` | `/components/Footer${`?${string}` | `#${string}` | ''}` | `/components/Header${`?${string}` | `#${string}` | ''}` | `/components/ListaDeCompromissos${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CriarAgendamento`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Compromisso`; params?: Router.UnknownInputParams; } | { pathname: `/components/DiaDaSemana`; params?: Router.UnknownInputParams; } | { pathname: `/components/Footer`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/ListaDeCompromissos`; params?: Router.UnknownInputParams; };
    }
  }
}
